# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	# create a master host
	config.vm.define "master" do |master|
		master.vm.hostname="master"
		master.vm.network "private_network", ip: "192.168.59.30"
		master.vm.provider "virtualbox" do |v|
		  v.name = "master"
		  v.memory = 512
		  v.cpus = 1
		end
		master.vm.provision "shell", inline: <<-SHELL
		  echo "master setup"
		SHELL
	end
    # create 2 slave hosts
	(1..2).each do |i|
		config.vm.define "node#{i}" do |node|
			node.vm.hostname="node#{i}"
			node.vm.network "private_network", ip: "192.168.59.3#{i}"
			node.vm.provider "virtualbox" do |v|
			  v.name = "node#{i}"
			  v.memory = 512
			  v.cpus = 1
			end
			node.vm.provision "shell", inline: <<-SHELL
			  echo "node#{i} setup"
			SHELL
		end
	end
	
	config.vm.provision "shell", inline:"sudo apt-get update"
	#config.vm.provision "shell", path:"./script/adduser.sh"
end
